### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by lennerd** [schmittjoh/cg-library#31]
Just wanted to know if this library is still actively maintained and if there is some kind of road map for new features and planed changes.

**Comment by schmittjoh** [comment]
There is no specific roadmap or features planned, but any compatibility fixes for newer PHP versions will be made.

If you need a specific feature that we don't have yet, feel free to open an issue and if it sounds good a pull-request is also welcome :)

**Comment by lennerd** [comment]
What do you think about ideas on how to refactor and hopefully improve the API and therefore create BCs? Does it make sense to open issues to discuss this? Do you have time to look through and think about suggestions at the moment?

Just don't want to bother you. 😉
